baseurl = "https://vickyd885.github.io/thoughts/"
locale = "en-us"
title = "Thoughts"
theme = "hugo-theme-terminal"

pagination.pagerSize = 5

[markup.goldmark.renderer]
  unsafe = true

[params]
  contentTypeName = "posts"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "Thoughts"
    copyright = ""

    [languages.en.params]
      subtitle = "Vicky's work and thoughts"
      keywords = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"

      [languages.en.params.logo]
        logoText = "vickyd885"
        logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories"
